### ISSUE TITLE
working Petrarch example

### ISSUE THREAD

**Issue by scottpez** [openeventdata/petrarch#94]
Hi,

Do you have a working example you can provide for the standalone Petrarch command line tool?

I tried running the example XML file at the bottom of this page  http://petrarch.readthedocs.org/en/latest/inputs.html  . The XML does not validate. It looks like the ```<EventCoding sourcecode="ARN" targetcode="GON" eventcode="064">``` tag does not have a closing tag. I'm not sure where to add the closing tag. I've tried closing it there ```<EventCoding sourcecode="ARN" targetcode="GON" eventcode="064"/>```, below ```</text>``` and below ```</parse>``` . In all cases the output of running the file with ```petrarch parse``` returns an empty output file.

Thank you very much for any assistance you can provide.
Scott

**Comment by johnb30** [comment]
@cnnorris Want to take a look at this?

**Comment by cnnorris** [comment]
Hi, 

Sorry for the unclear documentation. The `petrarch parse` command is supposed to be used when the syntactic parse is not available (which in most cases it isn't), but in this case the xml has the parse information, so you can run it with the `petrarch batch` command. Thanks for drawing our attention to this, I hadn't realized that the `batch` mode doesn't have a manual input, so I'll fix that real quick, and 
clear up the documentation as well. There should be a fixed version up within the next few hours. 

Also, if you're looking to code non-parsed text, I would suggest that you use [Hypnos](http://github.com/caerusassociates/hypnos), since this calls the Stanford CoreNLP suite more reliably than Petrarch, and has a much simpler API interface.

**Comment by scottpez** [comment]
Thank you for the quick reply and clarification. I appreciate you adding the batch command and documentation.

Yes, I am interested in coding non-parsed text.

I will take a look at Hypnos.

**Comment by johnb30** [comment]
Deprecation handled by https://github.com/openeventdata/petrarch/pull/95.
